snack = input("welcome to the melancholy munchie machine \n"
      "what mediocre snack would you like today? \n"
      "--------------- \n"
      "|    _____     | 1. $2.50 Radish \n"
      "|   | -_- |    | 2. $0.25 A Single Peanut (Unsalted)\n"
      "|   -------    | 3. $1.50 Mysteriously Murky Water™\n"
      "|              | 4. $0.50 Stale Bread (One Slice)\n"
      "|  1    2    3 | 5. $2.00 Plain Yogurt\n"
      "|  4    5    6 | 6. $3.00 Milk (Room Temperature)\n"
      "|  7    8    9 | 7. $4.00 Olive Garden Breadstick\n"
      "|              | 8. $5.00 Mystery Meat\n"
      "|  __________  | 9. $2.75 Celery Stick\n"
      "|              | \n"
      "---------------")
